# Debug mode lets you connect to the partyhall from another device
debug_mode: true

# Root path is where all the data related to the partyhall app are stored
root_path: './0_DATA/'

# Default mode can be either PARTYHALL or QUIZ
default_mode: 'PHOTOBOOTH'

web:
  listening_addr: 0.0.0.0:8039
  admin_password: "admin"

mosquitto:
  address: 127.0.0.1:1883

hardware_handler:
  baud_rate: 57600
  mappings:
    BTN_0: TAKE_PICTURE
    BTN_1: DISPLAY_DEBUG
    BTN_2: SHUTDOWN

photobooth:
  # If you have an hardware flash this should be set to true
  # Hardware flash are controlled by the arduino
  hardware_flash: false
  webcam_resolution:
    width: 1280
    height: 720

  # Default timer before taking a picture
  default_timer: 3

  # When set, the partyhall will take (without flash) a picture every x minutes
  # After the event you will be able to compile it in a short animated video
  # Set to zero to disable
  unattended_interval: 2
