# Debug mode lets you connect to the partyhall from another device
debug_mode: true

# Root path is where all the data related to the partyhall app are stored
root_path: './0_DATA/'

# Default mode can be either PARTYHALL or KARAOKE
default_mode: 'PHOTOBOOTH'

web:
  listening_addr: 0.0.0.0:8039
  admin_password: "admin"

mosquitto:
  address: mosquitto:1883

# This is the config for the command that controls the Arduino
hardware_handler:
  baud_rate: 57600
  mappings:
    BTN_0: photobooth/take_picture
    BTN_1: DISPLAY_DEBUG
    BTN_2: SHUTDOWN

spotify_client_id: ''
spotify_client_secret: ''

modules:
  - photobooth
  - karaoke