services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./.docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./0_DATA/mosquitto/data:/mosquitto/data
      - ./0_DATA/mosquitto/logs:/mosquitto/log

  backend:
    image: cosmtrek/air
    working_dir: /app
    volumes:
      - ./:/app
      - ./config.yaml:/etc/partyhall.yaml
    ports:
      - 8039:8039

  frontend:
    image: node:lts
    init: true
    volumes: ['./gui:/app']
    working_dir: '/app'
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - '127.0.0.1:5993:5173'
    command: ['bash', '-c', '[ ! -d node_modules ] && npm install; npm run dev -- --host']