services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./0_DATA/mosquitto/data:/mosquitto/data
      - ./0_DATA/mosquitto/logs:/mosquitto/log

  front:
    image: node:19-alpine
    working_dir: /app
    command: npm run dev
    volumes:
      - ./gui:/app
    ports:
      - 5993:5173
    extra_hosts:
      - "host.docker.internal:host-gateway"

  admin:
    image: node:19-alpine
    working_dir: /app
    command: npm run dev
    volumes:
      - ./gui_admin:/app
    ports:
      - 5994:5173
    extra_hosts:
      - "host.docker.internal:host-gateway"
