package utils

var (
	CURRENT_VERSION = "indev"
	CURRENT_COMMIT  = "XXXXXX"
)

const SOCKET_TYPE_BOOTH = "BOOTH"
const SOCKET_TYPE_ADMIN = "ADMIN"

var SOCKET_TYPES = []string{
	SOCKET_TYPE_BOOTH,
	SOCKET_TYPE_ADMIN,
}
