---
- hosts: 'all'
  become: yes
  tags: ['reboot']

  tasks:
    - name: 'Reboot to finish the setup'
      reboot:
        reboot_timeout: 1
        connect_timeout: 1
      async: 1
      poll: 0
      failed_when: false
      ignore_errors: true