---
- hosts: 'all'
  become: yes
  tags: ['mosquitto']

  tasks:
    - name: 'Install mosquitto'
      apt:
        name: [ 'mosquitto' ]

    - name: 'Make mosquitto listen on localhost'
      lineinfile:
        path: '/etc/mosquitto/mosquitto.conf'
        line: 'listener 1883 127.0.0.1'

    - name: 'Allow anonymous user on mosquitto'
      lineinfile:
        path: '/etc/mosquitto/mosquitto.conf'
        line: 'allow_anonymous true'

    - name: 'Enable & start mosquitto'
      systemd:
        name: 'mosquitto'
        enabled: yes
        state: 'restarted'