---
- hosts: 'all'
  tags: ['partyhall']

  tasks:
    - name: 'Adding the user to the serial group'
      become: yes
      user:
        name: '{{ansible_user}}'
        groups: ['dialout', 'audio', 'video', 'dip', 'plugdev', 'users', 'netdev', '{{ansible_user}}', 'wheel', 'adm', 'systemd-journal']

    - name: 'Make partyhall dirs'
      become: yes
      file:
        path: '/opt/partyhall'
        state: 'directory'
        mode: '0777'

    - name: 'Fetch the partyhall release URL'
      get_release_url: 
        repository: 'partyhall/partyhall'
      register: 'partyhall_url'

    - name: 'Downloading the latest release'
      become: yes
      get_url:
        url: '{{partyhall_url.meta}}'
        dest: '/opt/partyhall/partyhall'
        mode: '0777'

    - name: 'Symlink the executable'
      become: yes
      file:
        src: '/opt/partyhall/partyhall'
        dest: '/usr/bin/partyhall'
        state: 'link'

    - name: 'Pushing the partyhall config'
      become: yes
      template:
        src: 'templates/partyhall.yaml.j2'
        dest: '/etc/partyhall.yaml'
        mode: 0664

    - name: 'Creating the partyhall main dirs'
      file:
        path: '/home/{{ ansible_user }}/partyhall'
        state: 'directory'
        mode: '0777'

    - name: 'Pushing the partyhall user_settings config'
      template:
        src: 'templates/user_settings.yaml.j2'
        dest: '/home/{{ ansible_user }}/partyhall/user_settings.yaml'
        mode: 0664

    - name: 'Pushing the services (Partyhall)'
      become: yes
      template:
        src: 'templates/{{ item }}.service.j2'
        dest: '/usr/lib/systemd/user/{{ item }}.service'
        mode: '0644'
      loop: ['partyhall', 'hardware_handler']

    - name: 'Creating the pipewire config dirs'
      become: yes
      file:
        path: '/home/{{ ansible_user }}/.config/pipewire/pipewire.conf.d'
        state: 'directory'
        mode: '0777'

    - name: 'Copy the pipewire config'
      become: yes
      copy:
        src: 'files/pipewire_karaoke.conf'
        dest: '/home/{{ ansible_user }}/.config/pipewire/pipewire.conf.d/90-karaoke.conf'
        mode: '0644'

    - name: 'Enabling & restarting the services'
      systemd:
        name: '{{item}}'
        daemon_reload: yes
        state: 'restarted'
        enabled: yes
        scope: 'user'
      loop:
        - 'partyhall'
        - 'hardware_handler'
        - 'pipewire'
        - 'pipewire-pulse'

    - name: 'Initializing with the admin account'
      command: 'partyhall user create-admin --username "{{partyhall_admin_username}}" --password "{{partyhall_admin_password}}" --name "{{partyhall_admin_fullname}}"'