---
- hosts: all
  tags: [partyhall]

  tasks:
    - name: Make partyhall dirs
      become: yes
      file:
        path: /opt/partyhall
        state: 'directory'
        mode: '0777' # fck

    - name: Fetch the partyhall release URL
      get_release_url: 
        repository: partyhall/partyhall
      register: pburl

    - name: Downloading the latest release
      become: yes
      get_url:
        url: "{{pburl.meta}}"
        dest: /opt/partyhall/partyhall
        mode: '0777'

    - name: Symlink the executable
      become: yes
      file:
        src: /opt/partyhall/partyhall
        dest: /usr/bin/partyhall
        state: link

    - name: Pushing the partyhall config
      become: yes
      template:
        src: templates/partyhall.yaml.j2
        dest: /etc/partyhall.yaml
        mode: 0664

    - name: Make data directory
      file:
        path: "/home/{{ansible_user}}/data"
        state: directory
        mode: '0770'

    - name: Pushing the service
      become: yes
      template:
        src: templates/partyhall.service.j2
        dest: /usr/lib/systemd/user/partyhall.service
        mode: '0644'

    - name: Enabling the service
      systemd:
        name: partyhall
        daemon_reload: yes
        state: started
        enabled: yes
        scope: user