---
- hosts: 'all'
  tags: ['partyhall']

  tasks:
    - name: 'Install partyhall dependencies'
      become: yes
      apt:
        name: [ 'libvips', 'pavucontrol' ]

    - name: 'Adding the user to the serial group'
      become: yes
      user:
        name: '{{ansible_user}}'
        groups: ['dialout', 'audio', 'video', 'dip', 'plugdev', 'users', 'netdev', '{{ansible_user}}', 'wheel']

    - name: 'Make partyhall dirs'
      become: yes
      file:
        path: '/opt/partyhall'
        state: 'directory'
        mode: '0777' # fck

    - name: 'Fetch the partyhall release URL'
      get_release_url: 
        repository: 'partyhall/partyhall'
      register: 'partyhall_url'

    - name: 'Downloading the latest release'
      become: yes
      get_url:
        url: '{{partyhall_url.meta}}'
        dest: '/opt/partyhall/partyhall'
        mode: '0777'

    - name: 'Symlink the executable'
      become: yes
      file:
        src: '/opt/partyhall/partyhall'
        dest: '/usr/bin/partyhall'
        state: 'link'

    - name: 'Pushing the partyhall config'
      become: yes
      template:
        src: 'templates/partyhall.yaml.j2'
        dest: '/etc/partyhall.yaml'
        mode: 0664

    - name: 'Make data directory'
      file:
        path: '/home/{{ansible_user}}/data'
        state: 'directory'
        mode: '0770'

    - name: 'Make config directory'
      file:
        path: '/home/{{ansible_user}}/data/config'
        state: 'directory'
        mode: '0770'

    - name: 'Pushing the photobooth module config'
      become: yes
      template:
        src: 'templates/config_photobooth.yaml.j2'
        dest: '/home/{{ansible_user}}/data/config/photobooth.yaml'
        mode: '0644'

    - name: 'Pushing the karaoke module config'
      become: yes
      template:
        src: 'templates/config_karaoke.yaml.j2'
        dest: '/home/{{ansible_user}}/data/config/karaoke.yaml'
        mode: '0644'

    - name: 'Create the karaoke songs folder'
      file:
        path: '/home/{{ansible_user}}/data/karaoke'
        state: 'directory'
        mode: '0770'

    - name: 'Pushing the services (Partyhall)'
      become: yes
      template:
        src: 'templates/{{item}}.service.j2'
        dest: '/usr/lib/systemd/user/{{item}}.service'
        mode: '0644'
      loop: ['partyhall', 'hardware_handler']

    - name: 'Enabling the services'
      systemd:
        name: '{{item}}'
        daemon_reload: yes
        state: 'restarted'
        enabled: yes
        scope: 'user'
      loop: ['partyhall', 'hardware_handler']

    - name: 'Initializing with the admin account'
      command: 'partyhall user initialize --username "{{partyhall_admin_username}}" --password "{{partyhall_admin_password}}" --name "{{partyhall_admin_fullname}}"'