---
- hosts: 'all'
  tags: ['spotify']

  tasks:
    - name: 'Fetch the spotifyd release URL'
      get_release_url: 
        repository: 'Spotifyd/spotifyd'
      register: 'spotifyd_url'

    - name: 'Make spotifyd'
      become: yes
      file:
        path: '/opt/spotifyd'
        state: 'directory'
        mode: '0777' # fck

    - name: 'Downloading the latest release'
      become: yes
      get_url:
        url: '{{spotifyd_url.meta}}'
        dest: '/opt/spotifyd/spotifyd.tar.gz'
        mode: '0777'

    - name: 'Extracting spotifyd'
      become: yes
      unarchive:
        remote_src: yes
        src: '/opt/spotifyd/spotifyd.tar.gz'
        dest: '/opt/spotifyd/'

    - name: 'Symlink the executable'
      become: yes
      file:
        src: '/opt/spotifyd/spotifyd'
        dest: '/usr/bin/spotifyd'
        state: 'link'

    - name: 'Make config directory'
      file:
        path: '/home/{{ansible_user}}/.config/spotifyd'
        state: 'directory'
        mode: '0770'

    - name: 'Pushing the spotifyd config'
      template:
        src: 'templates/spotifyd.conf.j2'
        dest: '/home/{{ansible_user}}/.config/spotifyd/spotifyd.conf'
        mode: 0664

    - name: 'Pushing the services (spotifyd)'
      become: yes
      template:
        src: 'templates/spotifyd.service.j2'
        dest: '/usr/lib/systemd/user/spotifyd.service'
        mode: '0644'

    - name: 'Enabling the services'
      systemd:
        name: 'spotifyd'
        daemon_reload: yes
        state: 'restarted'
        enabled: yes
        scope: 'user'