---
- hosts: 'all'
  become: yes
  tags: ['plymouth']

  # This is black magic that barely works on real hardware
  # I how no clue how plymouth works
  # it sucks
  # *please help*
  # it does work on vm though
  tasks:
    - name: 'Install plymouth'
      apt:
        name: [ 'plymouth', 'plymouth-themes' ]

    - name: 'Copying the theme'
      copy:
        src: 'files/plymouth_theme/' # The final slash is important! It means copy the folder content not to a subfolder
        dest: '/usr/share/plymouth/themes/simple-image'

    - name: 'Setting up grub resolution'
      lineinfile:
        path: '/etc/default/grub'
        line: 'GRUB_GFXMODE={{grub_resolution}}'
        insertafter: '^#?GRUB_CMDLINE_LINUX='
        regexp: '^#?GRUB_GFXMODE='

    - name: 'Setting up grub cmdline'
      lineinfile:
        path: '/etc/default/grub'
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'

    - name: 'Setting up grub gfxpayload'
      lineinfile:
        path: '/etc/default/grub'
        regexp: '^GRUB_GFXPAYLOAD_LINUX='
        line: 'GRUB_GFXPAYLOAD_LINUX=keep'

    - name: 'Setting the plymouth theme'
      command: 'plymouth-set-default-theme -R simple-image'
      environment:
        PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin'

    - name: 'Updating the grub config'
      command: 'update-grub'
      environment:
        PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin'