name: Build Photobooth

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - uses: actions/checkout@v2
      - run: docker run -v $PWD:/app oxodao/oxbuilder:n19g19 bash -c "cd /app/gui && npm i && npm run build"
      - run: docker run -v $PWD:/app oxodao/oxbuilder:n19g19 bash -c "cd /app/gui_admin && npm i && npm run build"
      - run: docker run -v $PWD:/app oxodao/oxbuilder:n19g19 bash -c 'CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-X github.com/oxodao/photobooth/utils.CURRENT_VERSION=${GITHUB_REF##*/} -X github.com/oxodao/photobooth/utils.CURRENT_COMMIT=${GITHUB_SHA}" -o photobooth-${GITHUB_REF##*/}-linux-amd64 .'
      - run: docker run -v $PWD:/app oxodao/oxbuilder:n19g19 bash -c 'CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -ldflags="-X github.com/oxodao/photobooth/utils.CURRENT_VERSION=${GITHUB_REF##*/} -X github.com/oxodao/photobooth/utils.CURRENT_COMMIT=${GITHUB_SHA}" -o photobooth-${GITHUB_REF##*/}-linux-arm64 .'
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "photobooth-*-*-*"
          token: ${{ secrets.GITHUB_TOKEN }}
